---
- name: associating allocated public IP with the instance
  ec2_eip:
    device_id: "{{ item }}"
    ip: "{{ eip.public_ip }}"
    region: "{{ region }}"
  with_items: "{{ instance.instance_ids }}"
  register: elastic

- name: associated with the instance
  debug:
    var: elastic

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ elastic.results }}"
